DEBUG = true
export DEBUG

all:
    cd adm; make all;
    cd lib; make all;
    cd comm; make all;
    cd plg; make all;

clean:
	cd adm; make clean;
    cd lib; make clean;
	cd comm; make clean;
	cd plg; make clean;

rebuild: clean all

.PHONY: clean 
